# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-19 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(choices=[('android', 'Android Developer'), ('designer', 'Designer'), ('java', 'Java Developer'), ('php', 'PHP Developer'), ('python', 'Python Developer'), ('rails', 'Rails Developer'), ('wordpress', 'Wordpress Devloper'), ('ios', 'iOS Developer')], default='', max_length=50),
        ),
    ]
